const strings = {
  GET_STARTED: 'Get Started',
  SHOP_DAILY_GROCERY: 'Shop your daily grocery',
  THE_EASIEST_WAY:
    ' The easiest way to share your family’s grocery shopping-Try it out.',
  WELCOME_BACK: 'Welcome back',
  COUNTINUE_TO_SIGN_IN: 'Continue to sign in!',
  COUNTINUE_TO_SIGN_UP: 'Continue to sign up!',

  FORGET_PASS: 'Forgot Password?',
  CHECK_START: 'By signing up you agree to our ',
  CHECK_TERMS: 'terms & conditions ',
  CHECK_AND: 'and ',
  CHECK_PRIVACY: 'privacy policy',
  REMEMBER: 'Remember and keep me log in',
  NOACCOUNT_REGISTER: ' Don’t have Account',
  REGISTER: 'Sign up',
  LOGIN: 'Sign In',
  DAILY_GROCERY: 'Daily',
  GROCERY: 'Grocery Food',

  FILTER_ALL: 'All',
  FILTER_FRUITS: 'Fruits',
  FILTER_VEGETABLES: 'Vegetables',
  FILTER_FAST_FOOD: 'Fast-foods',
  PROFILE_NAME: 'Name',
  PROFILE_EMAIL: 'Email',
  DETAILS_SCREENAME: 'Details',
  WISHLIST_SCREENAME: 'WishList',
  CART_SCREENAME: 'Cart',
  QUANTITY: '0',
  ORDER_INFO: 'Order Info',
  SUB_TOTAL: 'Subtotal:',
  DELIVERY_FEE: 'Delivery fee:',
  DISCOUNT: 'Discount:',
  TOTAL: 'Total',
  CHECK_OUT: 'Checkout',
  AVAILABLE_STOCK: 'Available in stock',
  TERMS_AND_CONDITIONS: 'Terms and Conditions for Fruit Sales',
  My_PROFILE: 'My Profile',
  CHECKOUT: 'Checkout',
  ORDER_DETAIL: 'Order Detail',
};
export default strings;
